version: "3.5"
services:
  symbiote-nginx:
    image: symbioteh2020/symbiote-nginx
    ports:
    - 8102:8102
    networks:
    - symbiote
    secrets:
    - source: nginxngrok
      target: /home/nginx-ngrok.conf
    - source: nginxprod
      target: /home/nginx-prod.conf
    - source: nginxfullchaincert
      target: /certificates/fullchain.pem
    - source: nginxprivkeycert
      target: /certificates/privkey.pem
    environment:
    - SYMBIOTE_ENV=ngrok
    depends_on:
    - symbiote-rh
    - symbiote-rap
    - symbiote-aam
    - symbiote-monitor
secrets:
  nginxngrok:
    file: ./nginx-ngrok.conf
  nginxprod:
    file: ./nginx-prod.conf
  nginxfullchaincert:
    file: ./nginx-certificates/fullchain.pem
  nginxprivkeycert:
    file: ./nginx-certificates/privkey.pem

